// Generated by LiveScript 1.2.0
(function(){
  var fs, express, app, listFiles, omit, getMeta, getREADME;
  import$(global, require('prelude-ls'));
  import$(global, require('date-utils'));
  fs = require('fs');
  express = require('express');
  app = express();
  app.configure(function(){
    app.use(
    express['static'](__dirname + '/public'));
    app.engine('.haml', require('hamljs').render);
    app.set('view engine', 'haml');
  });
  app.get('/', function(req, res){
    var files;
    files = listFiles("public", ['js', 'css', 'bootstrap', '.DS_Store']);
    res.render('index', {
      locals: {
        files: files
      }
    });
  });
  listFiles = function(pa, excludes){
    var files;
    files = omit(fs.readdirSync(pa), excludes);
    return map(function(it){
      return getMeta(pa, it);
    }, files).sort(function(a, b){
      return a.mtime < b.mtime;
    });
  };
  omit = function(lst, n){
    n = n instanceof Array
      ? n
      : [n];
    return reject(function(it){
      return in$(it, n);
    }, lst);
  };
  getMeta = function(dir, name){
    var mtime;
    mtime = fs.statSync(dir + "/" + name).mtime;
    return listsToObj([['name', name], ['mtime', mtime], ['memo', getREADME(dir + "/" + name).replace(/(\r|\n|\r\n)/g, "<br/>")]]);
  };
  getREADME = function(pa){
    var t;
    t = fs.statSync(pa);
    if (t.isDirectory()) {
      if (fs.existsSync(pa + "/README")) {
        return fs.readFileSync(pa + "/README", "utf-8");
      } else {
        return "";
      }
    } else {
      return "";
    }
  };
  app.listen(
  process.env.PORT || 12345);
  if (app.settings.env === 'development') {
    console.log(
    "applications start");
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
  function in$(x, xs){
    var i = -1, l = xs.length >>> 0;
    while (++i < l) if (x === xs[i]) return true;
    return false;
  }
}).call(this);
